on: [push, pull_request]
name: ShellCheck

permissions:
  contents: read

jobs:
  konstruktoidShellCheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # master
      - name: Konstruktoid ShellCheck
        uses: ./action-shellcheck
