on: [push, pull_request]
name: ShellCheck

permissions:
  contents: read

jobs:
  konstruktoidShellCheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Konstruktoid ShellCheck
        uses: ./action-shellcheck
