on: [push, pull_request]
name: ShellCheck

permissions:
  contents: read

jobs:
  konstruktoidShellCheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Konstruktoid ShellCheck
        uses: ./action-shellcheck
